### ISSUE TITLE
（弱弱问下，和Ctrl+P启用路径匹配后有啥区别

### ISSUE THREAD

**Issue by Eragon-Brisingr** [hxhb/JumpTo#1]
![image](https://github.com/hxhb/JumpTo/assets/16950908/3e2e8443-8afe-42e2-94d6-80a1c16c1bda)

**Comment by hxhb** [comment]
1. AssetPicker没法直接跳转到目录
2. 如果只是想在ContentBrowser里找到这个资源，而不是想打开它，在AssetPicker里还要先打开才能跳转，比较繁琐。

而且它在工程里资源很多时唤出界面和搜索很卡，在我机器上要3s才能出来窗口。

**Comment by Eragon-Brisingr** [comment]
对不起我用Ctrl+P描述Open Asset快捷窗口有一定误导性，ContentBrowser一样可以开启Search Asset Path功能的，这样就不会存在上面提到的两个问题了

**Comment by hxhb** [comment]
哦，我理解你的意思了。其实和AssetPick的逻辑是一致的。
1. Search Asset Path实际上是资源搜索，而不是路径跳转
2. 要搜索的目录必须是当前ContentBrowser路径的子目录才能搜索的到

j2这个工具不是要替代它，而是辅助。

**Comment by Eragon-Brisingr** [comment]
嗯，谢谢答疑~
